Using: /home/mauricio/anaconda3/envs/r-environment/bin/ete3_apps/bin/Slr
Using: /home/mauricio/anaconda3/envs/r-environment/bin/ete3_apps/bin/codeml
Traceback (most recent call last):
  File "/home/mauricio/anaconda3/envs/r-environment/bin/ete3", line 33, in <module>
    sys.exit(load_entry_point('ete3==3.1.2', 'console_scripts', 'ete3')())
  File "/home/mauricio/anaconda3/envs/r-environment/lib/python3.6/site-packages/ete3-3.1.2-py3.7.egg/ete3/tools/ete.py", line 95, in main
  File "/home/mauricio/anaconda3/envs/r-environment/lib/python3.6/site-packages/ete3-3.1.2-py3.7.egg/ete3/tools/ete.py", line 269, in _main
  File "/home/mauricio/anaconda3/envs/r-environment/lib/python3.6/site-packages/ete3-3.1.2-py3.7.egg/ete3/tools/ete_evol.py", line 881, in run
  File "/home/mauricio/anaconda3/envs/r-environment/lib/python3.6/site-packages/ete3-3.1.2-py3.7.egg/ete3/evol/evoltree.py", line 302, in link_to_alignment
  File "/home/mauricio/anaconda3/envs/r-environment/lib/python3.6/site-packages/ete3-3.1.2-py3.7.egg/ete3/phylo/phylotree.py", line 434, in link_to_alignment
  File "/home/mauricio/anaconda3/envs/r-environment/lib/python3.6/site-packages/ete3-3.1.2-py3.7.egg/ete3/coretype/seqgroup.py", line 113, in __init__
  File "/home/mauricio/anaconda3/envs/r-environment/lib/python3.6/site-packages/ete3-3.1.2-py3.7.egg/ete3/parser/paml.py", line 155, in read_paml
Exception: Error reading sequences: Wrong format.
Mlig.23635 Mlig.23635
